# Generated by Django 3.1 on 2020-08-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProwlerOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=20)),
                ('check_id', models.FloatField()),
                ('check_title', models.CharField(max_length=200)),
                ('check_output', models.TextField()),
                ('result', models.CharField(choices=[('P', 'PASS'), ('F', 'FAIL'), ('I', 'INFO')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SeverityDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CISBenchmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_id', models.FloatField()),
                ('check_title', models.CharField(max_length=200)),
                ('aws_config_rule', models.CharField(max_length=100)),
                ('observation', models.CharField(max_length=200)),
                ('impact', models.CharField(max_length=200)),
                ('recommendation', models.TextField()),
                ('category', models.ManyToManyField(to='reports.CategoryDetails')),
                ('severity', models.ManyToManyField(blank=True, to='reports.SeverityDetails')),
            ],
        ),
    ]
