# Generated by Django 3.1 on 2020-08-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cisbenchmark',
            name='severity',
        ),
        migrations.AddField(
            model_name='cisbenchmark',
            name='severity',
            field=models.CharField(blank=True, choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('C', 'Critical')], max_length=1),
        ),
        migrations.DeleteModel(
            name='SeverityDetails',
        ),
    ]
