# Generated by Django 3.1 on 2020-08-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20200808_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cisbenchmark',
            name='severity',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('C', 'Critical')], max_length=1),
        ),
    ]
