# Generated by Django 3.1 on 2020-08-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20200808_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cisbenchmark',
            name='category',
            field=models.ManyToManyField(blank=True, to='reports.CategoryDetails'),
        ),
    ]
