# Generated by Django 3.1 on 2020-08-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20200808_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cisbenchmark',
            name='check_id',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='prowleroutput',
            name='check_id',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
