# Generated by Django 3.1 on 2020-08-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20200810_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cisbenchmark',
            name='severity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=10),
        ),
        migrations.AlterField(
            model_name='prowleroutput',
            name='result',
            field=models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL'), ('INFO', 'INFO')], max_length=5),
        ),
    ]
